server:
  port: 80

spring:
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    call-setters-on-nulls: true

--- #dev

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  config:
    activate:
      on-profile: dev