server:
  port: 80

spring:
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      location: C:\\Users\\rsh80\\Desktop\\temp
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

resource:
  path: file:///C:/Users/rsh80/Desktop/temp/

upload:
  path: /upload/**
--- #dev

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: elly
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false